### ISSUE TITLE
Update `clang` to 0.24

### ISSUE THREAD

**Issue by acrrd** [sunshine-protocol/dart-bindgen#2]
This crate cannot be compiled anymore because `clang` 0.23 fail to build because `clang-sys` 0.28.2 introduced a breaking change.
Updating the dependency to 0.24 will fix.

**Comment by acrrd** [comment]
Related to KyleMayes/clang-sys#114

**Comment by shekohex** [comment]
fixed in 1f487748b9ddc59d5124125638c0a779ea1312fa and new version and cli published too
