### ISSUE TITLE
Unable to build for MacOS

### ISSUE THREAD

**Issue by allenwyma** [sunshine-protocol/dart-bindgen#4]
Maybe I'm doing something wrong, but I'm getting this error:

```
--- stderr
  dyld: Symbol not found: __ZN4llvm14FoldingSetBase6anchorEv
    Referenced from: /usr/local/opt/llvm/lib/libclang.dylib
    Expected in: /Users/allen/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libLLVM.dylib
   in /usr/local/opt/llvm/lib/libclang.dylib
```

**Comment by shekohex** [comment]
is LLVM/Clang in your path? it seems that it can't link/find llvm.
could you try:
```
brew install llvm --with-clang
```
and try again?

**Comment by allenwyma** [comment]
Thanks for your reply, now I have when trying your above command from homebrew:

`Error: invalid option: --with-clang`

**Comment by shekohex** [comment]
> `Error: invalid option: --with-clang`

I guess the opposite? 
try 
` $ brew install --with-clang llvm` may make any difference.
if not working then just try `brew install llvm`
also, if you have XCode I guess you will have clang by default.

**Comment by allenwyma** [comment]
hi @shekohex i haven't forgotten about this, just wanted to let you know. Just I parked this to the side as I have something else to finish up in the meantime. I"ll get back to this. Please don't close :)

**Comment by shekohex** [comment]
Hello @HangingClowns, I'm sad to announce that I'll deprecate this crate in favor of the official one from the dart team [ffigen](https://github.com/dart-lang/ffigen) as it will be always up to date and maintained by them. and they will offer better support for it.

Feel free to close this issue.
Thank you.

**Comment by allenwyma** [comment]
hi @shekohex it's all good. looking forward to better FFI!

I'm also going to close this issue because, as you may have noticed, I've been way too busy to come back to this.
