### ISSUE TITLE
add support for ffi 1.0.0

### ISSUE THREAD

**Issue by peacess** [sunshine-protocol/dart-bindgen#7]

**Comment by shekohex** [comment]
Hi, I will try to work on this, this weekend!
and release a new version.

**Comment by peacess** [comment]
Efficient man, if any need, please let me know

**Comment by shekohex** [comment]
Hello @Peacess, I'm sad to announce that I'll deprecate this crate in favor of the official one from the dart team [ffigen](https://github.com/dart-lang/ffigen) as it will be always up to date and maintained by them. and they will offer better support for it.

Thank you again.
