### ISSUE TITLE
Update to clang ^1.0

### ISSUE THREAD

**Issue by tbraun96** [sunshine-protocol/dart-bindgen#9]
Other crates on crates.io sometimes depend on ``clang ^1.0``. When such a crate is required, it conflicts with the version selected in this crate

**Comment by shekohex** [comment]
Hello 👋
Sounds good, could you please create a PR for that? 
I'll review and merge it asap, then publish a new version.

Thanks!

**Comment by tbraun96** [comment]
Done! Thank you.

https://github.com/sunshine-protocol/dart-bindgen/pull/10

**Comment by shekohex** [comment]
Released in the latest version.

Btw you should see the #8 and switch to `ffigen` in the near future.
